name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Use the label of your self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Build Script
        run: |
          echo "Running on a self-hosted runner"
          uname -a
